services:
  nestjs-api: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  jsonserver:
    image: clue/json-server
    volumes:
      - ./db.json:/data/db.json
    ports:
      - '3001:80'